functionsDirectory = "D:\\Downloads\\doctorshtml\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "D:\\Downloads\\doctorshtml\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "node build.js"
functions = "D:\\Downloads\\doctorshtml\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]